---
title: "Untitled"
author: "SM"
date: "12/4/2015"
output: html_document
---

```{r, eval=FALSE}
require(rworldmap)
require(dplyr)
require(ggmap)

```


```{r}

newmap <- getMap(resolution = "low")

#buoyLocations <-dget("buoyLocationsFixed.txt")
#stormsToMap <- dget("stormsNorthAtl_NeuralNet.txt")
#weightedResults <- dget("completeWeightedMeans2.txt")

#stormsToMap <- stormsToMap %>% mutate(rowNum = as.numeric(rownames(stormsToMap)))

#stormsWithBuoyData <- left_join(weightedResults, stormsToMap, by="rowNum")

plot(newmap,xlim = c(-100,-30), ylim = c(0,55),  asp=1)
points(stormsWithBuoyData$Longitude, stormsWithBuoyData$Latitude, col= "blue", cex =0.6)
points(buoyLocations$Longitude, buoyLocations$Latitude, col = "red", cex = 0.6, pch=16)


```



```{r}

# before actually use filter out buoy data was NAs

Map <- qmap("north atlantic ocean", zoom = 3)

Map


Map + geom_point(aes(x = Longitude, y = Latitude, colour = Wind_WMO), 
                 data = stormsWithBuoyData) + 
  scale_colour_gradientn(colours=rainbow(4))

```
