---
title: "Storms and Buoys Data"
author: "SM"
date: "11/14/2015"
output: html_document
---

Need to compute weighted averages for variables for the set of buoys and add to the finalStorm dataset.

Next step is to loop over all of this to compute weighted averages for each year.


```{r, message=FALSE}

require(dplyr)
require(tidyr)
require(geosphere)
require(lubridate)

```


```{r}
#data from http://www.ncdc.noaa.gov/ibtracs/index.php?name=ibtracs-data
#ftp://eclipse.ncdc.noaa.gov/pub/ibtracs/v03r07/all/csv/year/


stormYearsFile <- c("2000.csv","2001.csv","2002.csv","2003.csv","2004.csv","2005.csv","2006.csv","2007.csv","2008.csv","2009.csv","2010.csv","2011.csv","2012.csv","2013.csv","2014.csv", "2015.csv")

allStorms <- vector("list",length(stormYearsFile)) 

#pull in csv files and assign to a list of datasets
for(i in 1:length(stormYearsFile)){
  
  allStorms[[i]] <-read.csv(paste("~/Comp-Stats-Project/storm",stormYearsFile[i], sep=""))
}

#only keep the first 19 columns
for(i in 1:length(allStorms)){
  allStorms[[i]] <- allStorms[[i]][,1:19]
}

#remove -999 from latitude and longitude
cleanStorms <- vector("list",length(stormYearsFile))

for(i in 1:length(allStorms)){
  cleanStorms[[i]] <- allStorms[[i]]%>% 
    filter(Latitude!=-999) %>% 
    filter(Longitude!=-999)
}

#all storms datasets have same order of variables
checkingStorms <- c()
for(i in 2:length(cleanStorms)){
  checkingStorms[i-1] <- sum(names(cleanStorms[[1]]) == 
                             names(cleanStorms[[i]]))
}


#combine all storm datasets into 1 big dataset
finalStorms <- cleanStorms[[1]]
for(i in 2: length(cleanStorms)){
  finalStorms <- rbind(finalStorms, cleanStorms[[i]])
}

#add new column of time in ymd_hms type setupt using parse date time fuction
finalStorms <- finalStorms %>% mutate(time = parse_date_time(ISO_time, "%m%d%Y %H%M")) %>%
  filter(year(time) != 1999)
```




```{r}


buoyLocations <- dget("buoyLocsAndYears.txt") 



for(k in 1:nrow(finalStorms)){
  
  firstRow <- finalStorms[k,]
  
  #col num for year of storm in that row
  yearColNum <- which(names(buoyLocations)==paste("year", year(firstRow$time), sep=""))
  
  buoyLocsThatYear <- buoyLocations %>% filter(buoyLocations[,yearColNum] == TRUE)
  
  
  stormCoords <- c(firstRow$Longitude, firstRow$Latitude)
  
    #function to compute dist from storm coord to buoy (buoy takes long/lat of buoy)
  computeDistanceTo <- function(buoy){
    return(distGeo(stormCoords,buoy))
  }
  
  #change 2e7 later
  buoyDists <- buoyLocsThatYear %>% mutate(distToStorm = 
             apply(cbind(Longitude, Latitude), 1, computeDistanceTo)) %>%
    filter(distToStorm <= 2e7) %>% select(BuoyNumber, distToStorm)
  
  #buoys
  buoyNumber <- buoyDists$BuoyNumber
  buoyYear <- year(firstRow$time)
  setOfBuoys <- vector("list",length(buoyNumber))
  
  #dataName <- seq(1,length(buoyNumber), by=1)
  
  
  
  
  matchingBuoys <- as.data.frame(matrix(nrow = 1,ncol =19))
  names(matchingBuoys) = c("YYYY", "MM", "DD", "hh", "WD", "WSPD", "GST", "WVHT", "DPD", "APD", "MWD", "BAR", "ATMP" ,"WTMP","DEWP" ,"VIS", "TIDE", "ymdday", "BuoyNumber")
  
  count <- 0
  count2 <- 0
  
  for(j in 1:length(buoyNumber)){
    site <- paste("http://www.ndbc.noaa.gov/view_text_file.php?filename=", buoyNumber[j], "h", buoyYear, ".txt.gz&dir=data/historical/stdmet/", sep ="")
  
    # call in data with try command in while loop
    i <- 1
    while (i < 2){
      data <- try(read.table(site,sep="", fill=TRUE, header=TRUE, comment.char=""))
      if (class(data) == "try-error") {
        next
      } else {
        i <- i + 1
      }
    }
  
  #if buoy data has comment sign (#) in variable names
  if(length(grep("X.",names(data)))>0){
    #ie names variable X.YY to YY
    names(data)[grep("X.",names(data))] <-
      substr(names(data)[grep("X.",names(data))],                                                start=3,nchar(names(data)[grep("X.",names(data))]))
    #removes row of units
    data <- data[-1,]
    
    #change YY to YYYY, WDIR to WD, PRES to BAR
    names(data)[grep("YY", names(data))] <- "YYYY"
    names(data)[grep("WDIR", names(data))] <- "WD"
    names(data)[grep("PRES", names(data))] <- "BAR"
    
    #remove mm (min col)
    data <- data[,-grep("mm", names(data))]
  }
    
  data <- as.data.frame(apply(data[,1:(length(data))], 2, as.numeric))
    
  #make new variable ymd_hms w lubridate (set all min 00 and sec to 00)
  nextRow<-data%>%mutate(ymdday=ymd_hms(paste(YYYY,"-", MM,"-",DD, "-", hh, "-", 00, "-", 00)))%>%
    filter(ymdday == firstRow$time)
  
  if(nrow(nextRow) > 0){
    nextRow <- as.data.frame(c(nextRow, buoyNumber[j]))
    names(nextRow)[ncol(nextRow)] <- "BuoyNumber"
    
  }
  
  
  if(j==1){
    matchingBuoys <- nextRow
  } else {
    matchingBuoys <- rbind(matchingBuoys, nextRow)
  }
  if(nrow(nextRow)==0){
   # count <- count + 1
  }
  #count2 <- count2 + 1
  
 # print(nextRow)
 # print(count2)
 # print(count)

  
  }
  
  matchingBuoys <- matchingBuoys %>% mutate(BuoyNumber = as.character(BuoyNumber))%>%left_join(buoyDists, by = "BuoyNumber")
  
  #need to fix averaging to deal w repeated rows or repeated parts of row ie 9 and 10 in this example
  
  #need to figure out what to do w 999 and 99 as missing data
  weightedByDistance <- function(x){
    return(weighted.mean(x, w= 1/(matchingBuoys$distToStorm), na.rm = TRUE))
  }
  
  
  meansForRow <- apply(matchingBuoys[,c(5:17)], 2, weightedByDistance)
  if(sum(meansForRow, na.rm=TRUE) > 0){
    meansForRow <- c(meansForRow, k)
    names(meansForRow)[length(meansForRow)] <- "rowNum"
    meansForRow <- as.data.frame(t(as.matrix(meansForRow)))
      if(k == 1){
      weightedMeans <- meansForRow
    } else {
      weightedMeans <- rbind(weightedMeans, 
                           meansForRow)
    }
  }
}

```



